Correct description for provisioned_concurrent_execution
The conditional in `main.tf`  checks against `-1` not `0` which I assume to be intentional, so this updates the description to reflect that case.

A zero value results in an error

    Error: expected provisioned_concurrent_executions to be at least (1), got 0


An alternative fix would be to change the ternary but I'm not sure what the intent there was